### ISSUE TITLE
http+docker://localhost - is it running?

### ISSUE THREAD

**Issue by MG-Token** [iShift/docker-compose-mtproxy#1]
@ubuntu:~/8/docker-compose-mtproxy$ docker-compose up -d
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

**Comment by MG-Token** [comment]
fixed
 sudo docker-compose up -d
Sorry for i took your time
i run it but its not config
its configed default data

**Comment by iShift** [comment]
yep, you should use sudo with docker, or add your username to docker group:
`sudo usermod -aG docker $USER`

https://docs.docker.com/install/linux/linux-postinstall/
