### ISSUE TITLE
Its run correctly but i cant connect from client

### ISSUE THREAD

**Issue by james12974** [iShift/docker-compose-mtproxy#3]
Hey its run correctly and logs is good
but i cant connect from client
why?
ports also is open in firewall

**Comment by iShift** [comment]
Hi! Need more info, can you see container in 'docker ps'?
can you open browser with you ip:port? you should get long waiting in browse

**Comment by james12974** [comment]
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS                    NAMES
3070e5e38c28        telegrammessenger/proxy:latest   "/bin/sh -c '/bin/ba…"   45 seconds ago      Up 44 seconds       0.0.0.0:6666->6666/tcp   docker-compose-mtproxy-master_telegram-proxy_1
and i cant brows ip:port

**Comment by iShift** [comment]
Look at https://github.com/iShift/docker-compose-mtproxy#change-proxy-port

> By default, proxy start at 443 port, if you want another - edit docker-compose.yml:
> 
> "443:443"

You should change **only** first (left) "433' port!

right one - not.
Because - left side - it is what port to use **outside** docker, right side - **inside** docker.

Telegram server **inside** docker always use 433

**Comment by james12974** [comment]
i also do the same with port 443:443 but i cant connect from client

**Comment by iShift** [comment]
try 8443:443, and check for open port (8443) on server

**Comment by james12974** [comment]
Oops i do this but problem still exist

**Comment by iShift** [comment]
do you restart container after change config?

**Comment by james12974** [comment]
yes i do

**Comment by james12974** [comment]
i try to load ip:port and the page still reloading

**Comment by iShift** [comment]
ok, post output of this commands:

- docker ps

- ps ax | grep 8443

- telnet 127.0.0.1 8443

(last command you also can do from remote PC with correct IP)

**Comment by james12974** [comment]
docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS                   NAMES
5772bb6c4914        telegrammessenger/proxy:latest   "/bin/sh -c '/bin/ba…"   56 seconds ago      Up 54 seconds       0.0.0.0:8443->443/tcp   newfolder3_telegram-proxy_1

ps ax | grep 8443
'ps' is not recognized as an internal or external command,
operable program or batch file.

telnet 127.0.0.1 8443
'telnet' is not recognized as an internal or external command,
operable program or batch file.

Oops

**Comment by iShift** [comment]
what OS you use? ps - it is standard Linux command for show process https://en.wikipedia.org/wiki/Ps_(Unix)

**Comment by james12974** [comment]
I use windows

**Comment by iShift** [comment]
on windows you should have telnet, this page should help you to check open port on windows https://www.howtogeek.com/howto/28609/how-can-i-tell-what-is-listening-on-a-tcpip-port-in-windows/

PS Windows (on server) - bad idea, very bad.

**Comment by james12974** [comment]
https://ibb.co/djzov8
i have this problems in ports
i also opened all local ports but problem still exist
Connection established from client after 2minutes trying.
but speed is very low and i cant download anything

**Comment by iShift** [comment]
@james12974 looks that this is problem with docker on windows, if you need to use windows server - install virtualbox with ubuntu and docker inside, or - replace windows

**Comment by james12974** [comment]
Ok
I got it on debian and this problem also is exist (Logs are good but i cant connect from client)

**Comment by james12974** [comment]
I run this commands and this is results : 
docker ps : 
CONTAINER ID        IMAGE                            COMMAND                  CR                                                                                       EATED             STATUS              PORTS                   NAMES
efcf8712aa34        telegrammessenger/proxy:latest   "/bin/sh -c '/bin/ba…"   4                                                                                        minutes ago       Up 4 minutes        0.0.0.0:8443->443/tcp   dockercomposemtpro   

ps ax | grep 8443 : 
 5222 ?        Sl     0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8443 -container-ip 172.18.0.2 -container-port 443
 5433 pts/0    S+     0:00 grep 8443


telnet 127.0.0.1 8443 : 
Trying 128.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.

**Comment by iShift** [comment]
@james12974  if you now use virtual box - you need to map virtual box port to you host post in VM settings, or use another connection type for get real IP inside debian
